---
- name: Playbook that create global variables that can be used by other playbooks in the workflow
  hosts: localhost
  gather_facts: no
  connection: local


  tasks:


  - name: create a file
    command: dd if=/dev/urandom bs=1048576 count=10 of=artefacts/bigfile

...