domain-include: .*
ignore-invalid-commands: true
crawl: true
auth-break: false
connection-types:
  - ssh
site-name: test
customer-name: New Company
ucdin: '91218238123'
devices:
  - 172.16.1.81-82
scan:
  timeout: 3
  count: 3
  interval: 0.5
  batch-size: 10
multi-process: false
inventory-merge: all
